### ISSUE TITLE
Fallback doesn't work on VLESS (X-UI, XRay)

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#1442]
Hello guys. I want to know **why fallback does not work on on X-UI** (XRay, VLESS+XTLS-Vision, own domain)?  

When I visit my (sub)domain with SSL on without port, it means 443 port right? But it does not load anything despite the fact VLESS inbound is set on port 443.

There is Caddy server behind X-UI, and it's pingable from X-UI's container. **After the unrecognizable client try to get (sub)domain page, VLESS should fallback to Caddy server, and Caddy should respond**.

Both containers are in the same network:

**caddy**:

```yaml
version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      # there are no exposed ports since VLESS fallbacks to Caddy, and Caddy listens only internally
    # ...
    env_file:
      - .env
    networks:
      - caddy-fallback
    # ...

networks:
  caddy-fallback:
    external: true
```

**X-UI**:

```yaml
---
version: "3.8"

services:
  xui:
    image: alireza7/x-ui
    container_name: xui
    ports:
      - 80:80
      - 443:443
      - "${XUI_DASHBOARD_PORT}:${XUI_DASHBOARD_PORT}"
      - "${XUI_WG_PORT}:${XUI_WG_PORT}/udp"
      - "${XUI_SS2022_PORT}:${XUI_SS2022_PORT}"
      - "${XUI_SUB_PORT}:${XUI_SUB_PORT}"
    env_file:
      - .env
    networks:
      - caddy-fallback
    # ...

networks:
  caddy-fallback:
    external: true
```

**`Caddyfile` config**:

```nginx
# ...

:{$FALLBACK_PORT_1} {
    import logging {$FALLBACK_PORT_1};
    respond "Handled by Caddy 1" 200
}

:{$FALLBACK_PORT_2} {
    import logging {$FALLBACK_PORT_2};
    respond "Handled by Caddy 2" 200
}
```

**Generated XRay config**:

```json
{
      "listen": null,
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "demouser@example.tld_vless",
            "flow": "",
            "id": "XXXX"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "alpn": "",
            "dest": "caddy:8081",
            "name": "",
            "path": "",
            "xver": 1
          },
          {
            "alpn": "h2",
            "dest": "caddy:8082",
            "name": "",
            "path": "",
            "xver": 2
          }
        ]
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled": true,
        "metadataOnly": false,
        "routeOnly": false
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/letsencrypt/live/<DOMAIN>/fullchain.pem",
              "keyFile": "/etc/letsencrypt/live/<DOMAIN>/privkey.pem",
              "ocspStapling": 3600
            }
          ],
          "cipherSuites": "",
          "maxVersion": "1.3",
          "minVersion": "1.2",
          "rejectUnknownSni": true,
          "serverName": ""
        }
      },
      "tag": "inbound-XXXXX"
    }
```

Again, the `caddy` container responds correctly and is pingable from X-UI, but X-UI somehow does not fallback to it:

```sh
/app # wget -qO- caddy:8081
Handled by Caddy 1
/app # wget -qO- caddy:8082
Handled by Caddy 2
```

So why is it not making fallback? Played with fallback's `alpn` setting (tried `h1`, `http/1.1`, `h2`), tried to change `dest` from `8081` to `caddy:8081` and so on - with no result.

log output with `alpn` set to `http/1.1`:

<details><summary>Details</summary>
<p>

```log
INFO - XRAY: [2794281990] proxy/vless/inbound: firstLen = 70
INFO - XRAY: [2794281990] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
INFO - XRAY: [2794281990] proxy/vless/inbound: realName = <DOMAIN>
INFO - XRAY: [2794281990] proxy/vless/inbound: realAlpn = h2
WARNING - XRAY: [2794281990] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to find the default "alpn" config
```

</p>
</details> 

log output with `alpn` set to `h2` or blank:

<details><summary>Details</summary>
<p>

```log
INFO - XRAY: [3520880892] proxy/vless/inbound: firstLen = 70
INFO - XRAY: [3520880892] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
INFO - XRAY: [3520880892] proxy/vless/inbound: realName = <DOMAIN>
INFO - XRAY: [3520880892] proxy/vless/inbound: realAlpn = h2
```

</p>
</details> 

Caddy itself uses `http/1.1`:

<details><summary>Details</summary>
<p>

```sh
/app # wget --server-response -O- caddy:8081
Connecting to caddy:8081 (172.19.0.3:8081)
  HTTP/1.1 200 OK
  Content-Type: text/plain; charset=utf-8
  Server: Caddy
  Date: Sun, 08 Sep 2024 18:36:29 GMT
  Content-Length: 18
  Connection: close
 ```

</p>
</details> 

VLESS settings screenshot: 
![2024-08-27_15-36-08](https://github.com/user-attachments/assets/34386478-9793-4650-b8f8-8f5bd6e793bd)

Why VLESS fallback not working?
