### ISSUE TITLE
warp issues

### ISSUE THREAD

**Issue by shenyiyouge** [alireza0/x-ui#1531]
Since I updated to Xray 24.12.18, my Warp stopped working. The original key became invalid, and replacing it with any new key also doesn't work. Please see the attached image,I’m not sure if others have this issue.
![微信截图_20241220081240](https://github.com/user-attachments/assets/ada76a05-364e-4569-a758-d7e3d4ecff32)

**Comment by mostafaznv** [comment]
It may have something to do with IPv6.
When I enable Warp, pinging, for example, instagram.com switches to IPv6 and then freezes.
However, without warp, it uses ipv4 and works as expected.

(Just thoughts, it might be wrong)

**Comment by mostafaznv** [comment]
I resolved my server issue with `warp/wireguard`.
I resolved my server issue with `warp/wireguard` and wanted to share my experience in case it helps someone.

For some reason, I had left `ipv6` unassigned on my VPS from the start. It worked fine until last night.
After troubleshooting through the panel, checking xray logs, and so on, I realized the issue might be related to ipv6.
To fix it, I assigned an IPv6 to my VPS and configured it using Netplan:


```
sudo nano /etc/netplan/50-cloud-init.yaml
```
```
network:
  version: 2
  ethernets:
    eth0:  # Replace 'eth0' with your network interface
      addresses:
        - 192.168.1.100/24  # Existing IPv4
        - 2001:db8::1/64    # Add your IPv6 here
      gateway4: 192.168.1.1
      gateway6: 2001:db8::1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888  # Google IPv6 DNS
          - 2001:4860:4860::8844
```
```
sudo netplan apply
```

And it worked.
