### ISSUE TITLE
connect multi ip

### ISSUE THREAD

**Issue by shyton** [alireza0/x-ui#385]
سلام
4 عدد ip به سرور من متصل است
چجوری می تونم هر یوزری که می سازم به یک ip وصل کنم ؟
توی حالت پیش فرض وقتی کانفیگ مجزا با دامین روی هر کدام از ip ها ست می کنم وقتی کاربر متصل میشه بازم ip اصلی سرور میگیره و ip که بهش وصل شده رو نمیگیره

**Comment by misagh72** [comment]
شما باید برای هر کدوم از ایپی ها یک ساب دامنه بسازید به توی کانفیگ به صورت مولتی دامنه قرار بدین

**Comment by alireza0** [comment]
درود بر شما
سوال مطرح شده کامل نبود. اگر میخواید خروجی هر کاربر با IP مربوط به خودش باشه، داستانش فرق داره:
برای هر سرویس (inbound) میشه روتینگ جداگونه درست کنید که از یکی از خروجی ها (outbounds) با IP مشحص استفاده کنه:

Outbound config:
```yaml
[
  {
    "protocol": "freedom",
    "tag": "output1",
    "sendThrough": "<ip1>",
    "settings": {}
  },
  {
    "protocol": "freedom",
    "tag": "output2",
    "sendThrough": "<ip2>",
    "settings": {}
  }
]
```

Routing rules Config:
```yaml
[
  {
    "inboundTag": ["inbound1"],
    "outboundTag": "output1",
    "type": "field"
  },
  {
    "inboundTag": ["inbound2"],
    "outboundTag": "output2",
    "type": "field"
  }
]
```

لطفا توجه داشته باشید که تگهایی که به صورت اتوماتیک توی پنل ساخته میشن به صورت زیر هستن:
```
inbound-<port>
```
Example for port 443:
```
inbound-443
```
