### ISSUE TITLE
Certificate setup at Docker Install

### ISSUE THREAD

**Issue by armin567ip** [alireza0/x-ui#666]
The caption says pretty much everything.

I did notice that the docker Install will create a folder in root and a folder called cert, I did copy paste my certificate there and in the panel I did type the exact location correctly.
But it keeps saying no such file or directory in the panel

**Comment by Enkidu-6** [comment]
You've either mapped the drives incorrectly or you're putting the wrong files in the folder. How are you running the image? docker or docker compose?

**Comment by Enkidu-6** [comment]
> it still show the same error, Where should I exactly place those files in my server, which directory?

If you're running the docker command from root then the files go in /root/certs/ on your server

**Comment by Enkidu-6** [comment]
Cool.
Again, I suggest using docker compose. Create a file and name it docker-compose.yml. Copy the following to the file and save.
```

version: "3.9"

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: YourDomain
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/certs/:/etc/certs/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
```
From the same directory type:
```
docker compose up -d
```
And you're done. Now you can stop or start the image any time without having to rebuild each time by typing:
```
docker compose stop
or
docker compose start
```
to update to the newest version type:
```
docker compose stop
docker system prune -a
docker compose up -d
```
this will update your panel to the newest version and the database and all your settings remain intact.
