### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/x-ui#943]
**Is your feature request related to a problem? Please describe.**
I created frontend that automates some actions like adding users, but this frontend cannot retrieve data since X-UI limits CORS to browser only. 

**Describe the solution you'd like**
I want to have a setting that allows requests from some domain to get access to API. It would be perfect if it would have been `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers` settings for panel listening port.

**Describe alternatives you've considered**
I tried:
1. Make frontend run through tunneling tools like `ngrok`, `zrok`, etc.
2. Browser extensions to allow CORS
3. Adding `Cors.io` proxies (or such) with no luck 

**Additional context**
Any help is welcomed!

**Comment by alireza0** [comment]
CORS is implemented in APIs which are used by panel itself.
Instead you should use API which could answer to all origins.

**Comment by Kenya-West** [comment]
Apparently, CORS error can be resolved if you run NGINX at any free port for API proxying purpose. The NGINX at port should proxy all requests to `localhost:port` or `domain:port` on port X-UI panel listens.

<details><summary>Details</summary>
<p>

Who wonders how I did this, examine this setup:
- `.env` file to store secrets (optional)
- All in Docker Compose;
- X-UI has SSL, domain set as host, no access by HTTP and is exposed on 443 for VLESS connection;
- Basic NGINX setup but with templates (templates are optional but better for distribution).

`.env`
```dotenv
DOMAIN=                         # Your domain
EMAIL=                          # E-mail that was set with your domain
XUI_HOSTNAME=                   # By default, X-UI dashboard's name is set to "yourhostname". You can change it to whatever you want.
XUI_DASHBOARD_PORT=54321        # Default: 54321. Check `docker compose logs x-ui` after starting it to see the port.
NGINX_API_REDIRECT_PORT=42069   # Nice. Port to access X-UI's API. Use whatever is free to use
```

I use templates, so `nginx.conf.template` would look like so:
```nginx
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# The part related to this issue: https://github.com/alireza0/x-ui/issues/943
server {
    listen ${NGINX_API_REDIRECT_PORT} ssl;
    http2 on;
    server_name ${DOMAIN};

    # Access and error logs.
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log info;
    
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # Preflight request handling
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        proxy_pass https://${DOMAIN}:${XUI_DASHBOARD_PORT}/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS headers
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
    }
}
```

`docker-compose.yml` is kind of this:
```yaml
---
version: "3.8"

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: ${XUI_HOSTNAME}
    volumes:
      - $PWD/db/:/etc/x-ui/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
      - ./static:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    env_file:
      - .env
    depends_on:
      - xui
    network_mode: host

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./static:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --non-interactive --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}

volumes:
  certbot-etc:
  certbot-var:
```

With this setup, you can access X-UI's API across the web.

</p>
</details>
